version: "3.5"
services:
  ${DOCKER_CONTAINER_NAME}:
    image: ${DOCKER_IMAGE_REPO}:${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_CONTAINER_NAME}
    network_mode: "host"
    cgroup_parent: "${DOCKER_CGROUP_PARENT}"
    volumes:
      - logitechmediaserver-config:/config
      - logitechmediaserver-playlist:/playlist
      - /data/INTERNAL:/music/INTERNAL:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: bind
        source: /mnt/NAS
        target: /music/NAS
        read_only: true
        bind:
          propagation: slave
      - type: bind
        source: /media
        target: /music/USB
        read_only: true
        bind:
          propagation: slave
    environment:
      - PUID=1000
      - PGID=1000
    restart: "no"
volumes:
  logitechmediaserver-config:
    external: true
  logitechmediaserver-music:
    external: true
  logitechmediaserver-playlist:
    external: true
